### PR TITLE
Add hints about local dev

### PR DESCRIPTION
**Pull request by joscha**

### CODE REVIEW

**Comment by apparentlymart** [comment]
Thanks again, @joscha!

This actually looks a bit different to my usual development setup. In my case I install this repo in my GOPATH and then hack on it in there. Like this:

```
cd $GOPATH
git clone git@github.com:yourname/terraform-buildkite.git src/github.com/saymedia/terraform-buildkite
cd src/github.com/saymedia/terraform-buildkite
```

I think this ends up the same as your way but avoids the need to temporarily hack the `import` statement as you suggested here.

**Comment by joscha** [comment]
^ this only works for you, because everyone else can not clone into a folder that is the same name as the import. Unless you don't clone your own fork, but add your fork as an extra remote I guess...

**Comment by apparentlymart** [comment]
@joscha the trick is to clone into the `saymedia` name even though you're not cloning *from* there. Notice how in my command line the first reference has `yourname` instead of saymedia.

Another way to do it is to `go get` it as normal and then add a new remote:

```
git remote add mine git@github.com:yourname/terraform-buildkite.git
```

Then when you push you just say "mine" instead of "origin".

Go doesn't actually care whether the git remote matches the import path... that's just `go get`'s default behavior, which you can override for development.

**Comment by joscha** [comment]
ah, got it - would you like me to update the example before merging?

**Pull request merged**
