### PR TITLE
Use dep to vendor imports

### PR DESCRIPTION
**Pull request by hattorious**
Pin to Terraform 0.11.7 since that's the most recent version.

### CODE REVIEW

**Comment by davidminor** [comment]
Hey @mavin, thanks for this!

What do you think about including only the lock & toml files, and not the vendor directory?

**Comment by apparentlymart** [comment]
Committing the vendor directory is the usual thing to do in Go with the current generation of tools.

This'll change once the new Go modules support is final, but it'll be only experimental in Go 1.11 so still some time with the old way for a while unless this codebase opts in to the optional modules experimental support.

To minimize friction, I would recommend going with the usual Go flow and checking in the vendor directory along with the metadata.

**Comment by davidminor** [comment]
Seems akin to checking in node_modules in a nodejs project, which you'd never do. But since I don't do much in go I'll take your word for it :)

**Comment by hattorious** [comment]
Thanks @davidminor & @apparentlymart for chiming in.

I'm doing work on this provider as a part of my current contract so if you want help managing it, then feel free to add me as a collaborator.

**Pull request merged**
