### PR TITLE
Remove `provider_settings` in favor of `github_settings` and `bitbucket_settings`

### PR DESCRIPTION
**Pull request by hattorious**
This is an implementation of the suggestions @apparentlymart made in https://github.com/saymedia/terraform-buildkite/issues/14#issuecomment-290820067

I might be abusing the json marshaler/unmarshaler but I'm less concerned about it since no one will be reusing this code.

@joscha please take a look

### CODE REVIEW

**Comment by joscha** [comment]
@mavin do I understand correctly that you introduce `bitbucket_settings` and `github_settings` in the state file only (the Buildkite API has no knowledge of these) and then change them back to match the API when you talk to BK?

**Comment by hattorious** [comment]
@joscha Correct; github and bitbucket settings are aggregates in the schema that the provider checks for changes, then sets at the `provider_settings` map on write and reads from `provider.settings`. It excludes the immutable state you mentioned (`provider.settings.repository` and additionally `provider.settings.account` for beanstalk repositories) on read.

The state diffs ~~you~~ we all were seeing are an indication of a couple different bugs/limitations of the Terraform schema that this change set attempts to mitigate.

**Comment by joscha** [comment]
Got it! That is great!

**Comment by joscha** [comment]
ping @apparentlymart

**Comment by michaelfoley1** [comment]
G'day friends.
Is it possible that this broke something?

I've been getting errors when attempting to apply or import previous pipelines for the past week.
```
* buildkite_pipeline.pipeline_name: 1 error(s) occurred:
* buildkite_pipeline.pipeline_name: buildkite_pipeline.pipeline_name: Invalid address to set: []string{"github_settings", "0", "separate_pull_request_statuses"}
```

Reverting `384041940a3b53bd14ccfab1c46f2c881167569a` cleared up the errors for me.

**Comment by joscha** [comment]
^ @davidminor thoughts?

**Comment by davidminor** [comment]
Possibly @mavin has some idea.

FYI I'm no longer at say media

**Comment by hattorious** [comment]
Sorry to say that this project is dead and probably won't be maintained any longer; see #25 for some context.

I'll see if I can find someone who still has admin access to this repo to archive it, and for now, it seems like [this fork](https://github.com/yougroupteam/terraform-buildkite) will be your best bet going forward or [this one](https://github.com/tink-ab/terraform-buildkite) which uses the beta GraphQL API.

**Pull request merged**
